#!/bin/bash
#
#OAR -l /nodes=1/core=1/,walltime=02:59:00
#OAR -E toto.stderr
#OAR -O toto.stdout
# The job use 1 nodes with one processor (core) per node,
#
# job duration is less than 2h59min
# The job needs  7000MB per core
# cd to the directory where the job was submitted
# ! By default, torque use the user's home directory

# Use the following command to go in your working directory (default is home)
#cd  /epi/asclepios2/mhadjham/OASIS_full/

# The job

iter2=`expr ${1} + 1`

Nb_att=`grep -v '^\s*$' /home/nmiolane/cluster/Scripts/OASIS_full/List_All.txt | wc -l`

Nb_ex=`ls -l /home/nmiolane/cluster/Scripts/OASIS_full/BCH_Atlas_t0_guimond/SVF_0*_${1}_p1.2.mha | wc -l`

# attente de la creation de toutes 

while [ "${Nb_ex}" != "${Nb_att}" ]; do
sleep 10
Nb_ex=`ls -l /home/nmiolane/cluster/Scripts/OASIS_full/BCH_Atlas_t0_guimond/SVF_0*_${1}_p1.2.mha | wc -l`
done

#My Mean Vect
#/home/mhadjham/MyMeanVect/./myMeanVect /home/nmiolane/cluster/Scripts/OASIS_full/BCH_Atlas_t0_guimond/SVF_0*_${1}.mha /home/nmiolane/cluster/Scripts/OASIS_full/BCH_Atlas_t0_guimond/Mean_SVF_${1}.mha
/home/nmiolane/cluster/Scripts/OASIS_full/myMeanVect2D/./myMeanVect /home/nmiolane/cluster/Scripts/OASIS_full/BCH_Atlas_t0_guimond/SVF_0*_${1}_p1.2.mha /home/nmiolane/cluster/Scripts/OASIS_full/BCH_Atlas_t0_guimond/Mean_SVF_${1}_p1.2.mha


